# Generated by Django 5.2.6 on 2025-09-14 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_marks', models.IntegerField(default=0)),
                ('content_marks', models.IntegerField(default=0)),
                ('conclusion_marks', models.IntegerField(default=0)),
                ('handwriting_marks', models.IntegerField(default=0)),
                ('grammar_marks', models.IntegerField(default=0)),
                ('special_points', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='participants.participant')),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'evaluator')},
            },
        ),
    ]
