[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm config set fund false",
  "npm config set audit false", 
  "npm ci --omit=dev || npm install --omit=dev"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "5001"
